import type { Metadata } from "next";
import { Noticia_Text } from "next/font/google";
import "./globals.css";
import { AI } from "./actions";

const font = Noticia_Text({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <AI>{children}</AI>
      </body>
    </html>
  );
}
